### ISSUE TITLE
Old build detected error message

### ISSUE THREAD

**Issue by Cossey** [Fmstrat/pushover-desktop#2]
A error displays on load in Windows 10 about the app being built a long time ago and that it should be rebuilt:

![image](https://user-images.githubusercontent.com/6280250/132123495-09b2849c-18e7-4e01-ae03-5034a3704d8b.png)

**Comment by BigWebstas** [comment]
Fixed on my fork
https://github.com/BigWebstas/pushover-desktop/releases/tag/v1.2

**Comment by toonymak1993** [comment]
Thank you very much for this. It works very cleanly. Very good work

**Comment by tellice** [comment]
I have updated to the v1.2 above, and its been running great for months. But since yesterday, i am getting the same error message as above every time pushover application starts:

Old Build detected
This app was built a long time ago. Nativefier uses the chrome browser (through Electron) and it is insured to keep using an old version of it. Please upgrade nativefier and rebuild this app.

Are you able to work your magic again?

**Comment by fischy667** [comment]
I build it with nativefier v50.01. Enjoy.

[Pushover-Desktop_nativefier-v50](https://github.com/fischy667/pushover-desktop/releases/tag/nativefier_v50)

**Comment by DrSpaldo** [comment]
> I build it with nativefier v50.01. Enjoy.
> 
> [Pushover-Desktop_nativefier-v50](https://github.com/fischy667/pushover-desktop/releases/tag/nativefier_v50)

I'm still getting old build with this one as well @fischy667

**Comment by fischy667** [comment]
New rebuild it with nativefier v50.1.0.

[Pushover-Desktop_nativefier-v50.1](https://github.com/fischy667/pushover-desktop/releases/tag/nativefier_v50.1)
